# Runs steps to generate and publish code coverage data

parameters:
  OpenCppCoverageExe: '$(Build.BinariesDirectory)\OpenCppCoverage\OpenCppCoverage.exe'
  GitCommitHash: $(OnnxRuntimeGitCommitHash)
  PublishReport: true
  PostToDashBoard: false
  ContinueOnError: false
steps:

- task: PowerShell@2
  displayName: 'Run Test Coverage'
  inputs:
    filePath: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\run_OpenCppCoverage.ps1'
    arguments: '-OpenCppCoverageExe:"${{parameters.OpenCppCoverageExe}}" -SourceRoot:"$(Build.SourcesDirectory)" -BuildRoot:"$(Build.BinariesDirectory)" -LocalBuild:$true'
  continueOnError: ${{parameters.ContinueOnError}}  

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.BinariesDirectory)/**/cobertura.xml'
    reportDirectory: '$(Build.BinariesDirectory)/**/OpenCppCoverageResults'
  continueOnError: ${{parameters.ContinueOnError}}
  condition: ${{parameters.PublishReport}}

- task: CmdLine@1
  displayName: 'Install mysql-connector-python conda module'
  inputs:
    filename: '$(Build.BinariesDirectory)\packages\python\scripts\conda.exe'
    arguments: 'install -q --insecure -y mysql-connector-python'
  timeoutInMinutes: 10

- task: PythonScript@0
  displayName: 'Generate cmake config'
  inputs:
    scriptPath: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\post_code_coverage_to_dashboard.py'
    arguments: --commit_hash=${{parameters.GitCommitHash}} --report_file="$(Build.BinariesDirectory)/Debug/Debug/cobertura.xml" --report_url="https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=$(Build.BuildId)"
    workingFolder: "$(Build.BinariesDirectory)"
  continueOnError: ${{parameters.ContinueOnError}}
  condition: ${{parameters.PostToDashBoard}}
  env: 
    DASHBOARD_MYSQL_ORT_PASSWORD: $(dashboard-mysql-ort-password)
